### ISSUE TITLE
Unable to SendVideoFrame

### ISSUE THREAD

**Issue by SebastianKunz** [WonderMediaProductions/webrtc-dotnet-core#2]
Hello,
I am developing a C# console application that is able to establish a peer connection with a browser. As of now I am able to transfer data via a data channel. My signaling is based on websockets. The idea is that my C# application captures a WPF application and streams it to the peer in the browser. The peer in the browser can then control that application.
This is how I establish the connection.

```
private readonly WebSocket _socket;
private readonly PeerConnection _peer;
private int _id = -1;
private readonly VideoTrack _videoTrack;
private readonly int _width = 400;
private readonly int _height = 400;
private int _frameRate = 60;
private Bitmap _redBitmap;

public Streamer(PeerConnectionOptions options)
{
  _peer = new PeerConnection(options);
  _peer.AddDataChannel(new DataChannelOptions());

  _socket = new WebSocket("wss://localhost:8080");

  #region WebSocket Callbacks
  //implementing websocket callbacks
  #endregion

  #region PeerConnection Callbacks
  //implementing peerconnection callbacks
  #endregion

  _videoTrack = new VideoTrack(_peer, VideoEncoderOptions.OptimizedFor(_width, _height, 
  _frameRate));

  videoTrack.LocalVideoFrameProcessed += (pc, trackId, pixels, isEncoded) =>
  {
  };
}
```
Before capturing the screen I want to take a step back and just transmit a red image. 
So I create a red bitmap.
```
public void CreateRedBitmap()
{
  var bmp = new Bitmap(_width, _height);
  using (var gfx = Graphics.FromImage(bmp))
  using (var brush = new SolidBrush(Color.FromArgb(255, 0, 0)))
  {
    gfx.FillRectangle(brush, 0, 0, _width, _height);
  }
  _redBitmap = bmp;
}
```
This is how I send the generated bitmap to the remote peer.
```
public void SimulateFrame()
{
  lock (sendlock)
  {
    Console.Write(".");
    var data = _redBitmap.LockBits(new Rectangle(0, 0, _width, _height), 
                        ImageLockMode.ReadWrite,
                        PixelFormat.Format32bppArgb);

    _videoTrack.SendVideoFrame(data.Scan0, data.Stride, data.Width, data.Height, 
                                                    VideoFrameFormat.Argb32);
    
    _redBitmap.UnlockBits(data);
  }
}
```
And this is the main of my application.
```
static void Main(string[] args)
{
  var streamer = new Streamer(new PeerConnectionOptions());

  streamer.Start();
  streamer.CreatePeerOffer();
  streamer.CreateRedBitmap();
  var startTimeSpan = TimeSpan.Zero;
  var periodTimeSpan = TimeSpan.FromSeconds(1 / 60.0);
				
  //send 60 frames per second
  var timer = new System.Threading.Timer((e) =>
  {
    streamer.SimulateFrame();
  }, null, startTimeSpan, periodTimeSpan);

  Console.ReadKey();
}
```
So the way my application works is that the Streamer (C#) offers his stream. The node server saves that information and whenever there is a Receiver (JS/Browser) requesting that specific Streamer via an ID it exchanges sessiondescriptions and icecandidates, to establish the connection. This works fine when not sending any frames.

However as soon as the connection is established and I try to send frames (as of now the streamer tries to send frames also when there is no connection) the application crashes. 

This is the error I'm getting.
```
# Fatal error in: c:\users\sebastian\desktop\webrtc-dotnet-core\webrtc-native\nvencoderh264.cpp, line 230
#RTC INFO:  (data_channel.cc:366): DataChannel received OPEN_ACK message, sid = 1
last system error: 0
# Check failed: frame_buffer->type() == VideoFrameBuffer::Type::kNative
```
It seems like that my pixel format is not matching. I'm using Argb32. Is this not supported by this project? What pixelformats are supported? Are they the same for nvenc?

**Comment by ziriax** [comment]
Sorry, the library is still rather rough around the edges currently.

Until we have a proper `PeerConnectionFactory`, you need to globally configure what kind of video codec you want to use.

By default it will use the hardware H264 NVENC encoder from NVidia, assuming you pass a DirectX hardware texture (hence the assertion). Does your system have an NVidia card?

If so, I would recommend changing the call to `SendVideoFrame` by:

```CS

var format = PeerConnection.SupportsHardwareTextureEncoding
                ? VideoFrameFormat.CpuTexture
                : VideoFrameFormat.Bgra32;

 _videoTrack.SendVideoFrame(data.Scan0, data.Stride, data.Width, data.Height, format);
```

If that doesn't work, you can force the VP8 software encoder to be used instead:

```CS
PeerConnection.Configure(new GlobalOptions
                {
                    ForceSoftwareVideoEncoder = true,
                });
```

**Comment by SebastianKunz** [comment]
Thank you for your quick answer!

My system does have a NVIDIA GPU (GTX 1060). When I try your first suggestion I get `NVENC H264 encoder does not support format 4.` It seems like that only GpuTextureD3D11 is supported.

When I use `ForceSoftwareVideoEncoder = true` then I get `System.Exception: 'Configure failed'`. Is there anything I have am missing?

**Comment by ziriax** [comment]
Ouch, it seems the developer that removed the `NvPipe` support didn't implement `CpuTexture`... So that's a regression bug.

Currently you have to call `Configure` before doing anything else, and you can only call it once.

**Comment by SebastianKunz** [comment]
That's a bummer. Ok calling `Configure` before solved the issue. Now there is a new exception thrown.
It turns out that `NativeVideoBuffer` does not support converting into `I420` format. `"Converting a native buffer to a CPU 420 buffer is not supported"`.
Is there currently a way to utilize bitmaps or do I have to stick to D3D11 Textures?

**Comment by ziriax** [comment]
Sorry, I forgot to mention that forcing software encoding doesn't change `PeerConnection.SupportsHardwareTextureEncoding`...

So you have to pass `VideoFrameFormat.Argb32` again to `SendVideoFrame`, because otherwise the peer encoder will use a VP8 encoder, but will get a native buffer, and the encoder doesn't know how to handle that ;-)

This part of the API is not well designed yet.

You are the first external user of this library, so expect glitches!

**Comment by SebastianKunz** [comment]
That worked for me! Thank you for your support :)

**Comment by ziriax** [comment]
Nice! Sorry for the bumpy ride. Please note that for maximum performance, we do advice sending GPU textures (only NVENC and Direct3D11 supported for now)
